### ISSUE TITLE
dont working in ie11

### ISSUE THREAD

**Issue by helight59** [chrisnunes57/Draggin.js#1]
sets wrong value

![image](https://user-images.githubusercontent.com/20089885/58358100-1be1a180-7e86-11e9-99cf-5f1b624f6132.png)

**Comment by chrisnunes57** [comment]
Nice catch! Looks like an issue with getBoundingClientRect not working in IE. I'll fix it later today.

**Comment by chrisnunes57** [comment]
Should be fixed @helight59

**Comment by helight59** [comment]
thanks!
